### ISSUE TITLE
HTL: Add support  for "/libs/granite/sightly/templates/clientlib.html"

### ISSUE THREAD

**Issue by deeprim** [aemtools/aemtools#133]
"/libs/granite/sightly/templates/clientlib.html" template should be proposed as `data-sly-use` option.

Once it selected in `data-sly-use`, it should be proposed in `data-sly-call`:

* js
* css
* all

Once it selected in `data-sly-call`, corresponding "Template Arguments" should be proposed in `data-sly-call` options:

* categories

For `categories` option clientlibs available in the project should be proposed as completion variants

* [x] Add `/libs/granite/sighlty/templates/clientlib.html` for `data-sly-use` completion
* [x] Add index for all clientlibs in the project
* [x] `data-sly-call` for `clientlib.html` should have completion for `js` & `css`
* [x] "Options" completion for either `js` or `css` should have `categories` as "top" variant
* [x] Completion for `categories` option should have all clientlibs available in project (clientlibs that have "embed" attribute should go first)
* [x] Quick doc action should be available for categories value (e.g. `categories='<caret>my-cat'`). The documentation should reveal all data regarding selected category

**Comment by dmitry-cherkas** [comment]
I guess, it would be a better option to index all OOTB AEM templates and use this index for auto-suggest.

**Comment by deeprim** [comment]
Hi @dmitry-cherkas ,

Though, the indexing of OOTB AEM templates sounds like a good feature. 
The specific semantics (the clientlibs template should be called with client libs, the category) could not be indexed, i.e. required to be implemented anyway

**Comment by deeprim** [comment]
The completion is broken, reopened

**Comment by koha26** [comment]
@deeprim 
I fixed documentation in scope of https://github.com/aemtools/aemtools/pull/205. In addition, I added documentation for categories, embeds, dependencies in the clientlibs folder.

Also, completion has been fixed in 07768bf06e9ff10033611bea4c62c03288402731 commit. 
Now, all items from the list in the description work as expected.
