### ISSUE TITLE
Unsynchronized osgi configs when they removed

### ISSUE THREAD

**Issue by OleksiiChuiev** [aemtools/aemtools#151]
It seems that plugin doesn't synchronize current state of OSGi configs. Before removing one it renders all links fine, but after that one of link replaced with label "INVALID". Preconditions: Service class opened in IDEA, one of the configs for this class removed.
Before:
![image](https://user-images.githubusercontent.com/34628517/34082252-6f74d4a8-e363-11e7-98ef-7fa842f98cda.png)
After:
![image](https://user-images.githubusercontent.com/34628517/34082257-787d4184-e363-11e7-8dee-4870e400ada8.png)

**Comment by koha26** [comment]
Will be fixed in 0.9.2.
