### ISSUE TITLE
Common: add support for AEM Groovy Console

### ISSUE THREAD

**Issue by deeprim** [aemtools/aemtools#168]
Completion for groovy scripts intended for usage via [aem-groovy-console](https://github.com/OlsonDigital/aem-groovy-console)

* [ ] - ability to mark an arbitrary groovy as "AEM Groovy Console" file (investigation required)
* [ ] - once a groove file is marked as "AEM Groovy Console" file code completion & code navigation should be available (e.g. using gdsl file)
* [ ] - "AEM Groovy Console" should have "Run" button that will allow to execute the script within selected AEM instance (via select menu)

**Comment by bobi** [comment]
i'm not sure that it should be part of aemtools as this is not core aem functionality and there more tools except groovy console that can run scripts, but just in case https://github.com/bobi/aem-groovyconsole-plugin

**Comment by koha26** [comment]
@bobi, thank you for your comment. Yes, you are right. It is not required anymore, because there is a good analog. This ticket was created when there was no aem groovy console plugin.
