### ISSUE TITLE
HTL: add versioning of HTL

### ISSUE THREAD

**Issue by deeprim** [aemtools/aemtools#171]
HTL has different capabilities depending on it's version, plugin should be able to deal with specific HTL version

Info:
https://github.com/Adobe-Marketing-Cloud/htl-spec/issues/55

- [x] Settings panel
- [x] Notification about used versions

Features to hightlight
- [x]  data-sly-set
- [x]  data-sly-unwrap attribute identifier and value
- [x]  data-sly-list and data-sly-repeat options: begin, step and end
- [x]  relational operator in

**Comment by koha26** [comment]
Can be configured via https://plugins.jetbrains.com/docs/intellij/settings-tutorial.html#testing-the-custom-settings-plugin
