### ISSUE TITLE
HTL: Improve completion for component

### ISSUE THREAD

**Issue by deeprim** [aemtools/aemtools#172]
Improve completion for `component` context object

e.g.
```
${component.properties.<caret>} <- here should be presented list of properties declared in corresponding cq:Component xml
```

Component property should contain a reference to it's declaration 

Find usages triggered on component property within .content.xml file should reveal all it's usages from htl files

* [x] - Add completion for `component.properties`
* [x] - Add reference into `component.properties.property`
* [ ] - Implement `Find Usages` for component properties

**Comment by koha26** [comment]
@deeprim Implemented 2 items from the list, but don't understand the last one. I don't understand the purpose of it. I think the reference to the dialog property is enough. Or did you have another point of view?
