### ISSUE TITLE
OSGI: add validation of OSGi annotations

### ISSUE THREAD

**Issue by vhonchar** [aemtools/aemtools#174]
Sometime, there are situations, when developer can add service with metadata == true, but do not add any property. To avoid that, it is good to support such validation rules directly in Intellij.

Use case:
1) Open any implementation of OSGi service
2) Add property "metadata = true" into @Component

Expected: line with component annotation should be highlighted as warning with appropriate message.

Note.
List of actual rules could be taken from maven-bundle-plugin.

**Comment by koha26** [comment]
Will be added in 0.9.2.
