### ISSUE TITLE
IntelliJ 2018.3: Icons of file type "HTL" in wrong size!

### ISSUE THREAD

**Issue by felixmueller** [aemtools/aemtools#179]
After Upgrading to IntelliJ 2018.3, the Icons for the file type "HTL" are twice as big as normal. See attached Screenshot.
<img width="624" alt="intellij-2018-1 3-htl-icon-size" src="https://user-images.githubusercontent.com/115331/49003560-72358800-f162-11e8-9952-d66e411c9140.png">

**Comment by deeprim** [comment]
Hi @felixmueller,
Thanks for the report!

**Comment by deeprim** [comment]
Hi @sergikoff,
Version *v0.9.0.1* was submitted for release, it will be available for download from IntelliJ Plugin Repository in 1-3 days (in meantime, you could download and install it manually from [release page](https://github.com/aemtools/aemtools/releases/tag/v0.9.0.1)),
Thank you

**Comment by felixmueller** [comment]
Hi @deeprim ,
thank you very much for fixing! I just installed the new version and everything look great again!
Cheers,
Felix
