### ISSUE TITLE
IDE: resolve OSGi configs (Standard)

### ISSUE THREAD

**Issue by deeprim** [aemtools/aemtools#84]
Resolve OSGi configs for services declared with [OSGi R6 annotations](https://mvnrepository.com/artifact/org.osgi/osgi.annotation/6.0.1)

- [x] Added reference between class with R6 annotation with OSGI config
- [x] Added reference between R6 service config properties and OSGI config values

**Comment by koha26** [comment]
Will be included in 0.9.2.
